# 9865, over rides only if needed, ie. TX2..
PCA9685_I2C_ADDR = 0x40
PCA9685_I2C_BUSNUM = 1

# STEERING
STEERING_CHANNEL = 1
STEERING_LEFT_PWM = 240
STEERING_RIGHT_PWM = 500

# THROTTLE
THROTTLE_CHANNEL = 0
THROTTLE_FORWARD_PWM = 420
THROTTLE_STOPPED_PWM = 380
THROTTLE_REVERSE_PWM = 330

# VEHICLE
DRIVE_LOOP_HZ = 20
MAX_LOOPS = 60

# JOYSTICK
USE_JOYSTICK_AS_DEFAULT = True

# CAMERA
CAMERA_TYPE = 'PICAM'   # (PICAM|WEBCAM|CVCAM|CSIC|V4L|D435|MOCK|IMAGE_LIST)
IMAGE_W = 160
IMAGE_H = 120
# IMAGE_DEPTH = 3         # default RGB=3, make 1 for mono
# CAMERA_FRAMERATE = DRIVE_LOOP_HZ
# CAMERA_VFLIP = False
# CAMERA_HFLIP = False
